name: CI
on:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    container: denoland/deno
    env:
      POSTGRES_PASSWORD: pg_pwd
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: deno run -A abc.ts      
        env:
          PG_URL: pg://postgres:${{env.POSTGRES_PASSWORD}}@postgres:5432/postgres'
