name: push
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: |
          {
            echo 'GLOB<<EOF'
            echo ab
            echo cd
            echo EOF
          } >> $GITHUB_OUTPUT
        id: aaa
      - run: echo ${{steps.aaa.outputs.GLOB}}
      - run: ls
        working-directory: ./.vscode
      - run: |
          pwd
          cd ..
      - run: pwd
