name: push
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          {
            echo 'GLOB<<END'
            echo ab
            echo ls
            echo END
          } >> $GITHUB_OUTPUT
        id: aaa
      - run: echo ${{steps.aaa.outputs.GLOB}}

      - name: Get File List
        id: get_files
        run: |
          {
            echo 'GLOB<<END'
            cat abc.ts
            echo END
          } >> $GITHUB_OUTPUT

      - run: echo ${{steps.get_files.outputs.GLOB}}