name: CI
on:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: pg_pwd
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2
      - run: deno run -A abc.ts
        env:
          PG_URL: pg://postgres:${{env.POSTGRES_PASSWORD}}@127.0.0.1:5432/postgres
