name: CI
on:
  push:
    branches:
      - "*"
jobs:
  build:
    if: false
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        uses: actions/checkout@v3
      - name: Setup-deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run
        run: |
          echo ::group::Deno cache
          deno run -A ./.github/scripts/publish.ts
        env:
          GITHUB_TOKEN: ${{secrets.CI_GITHBU_TOKEN}}
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload
        uses: asnowc/actions@upload-artifact/v1
        with:
          path: list.json
          name: dist-c
