name: CI
on:
  push:
permissions:
  contents: write
  actions: write
  statuses: write
  checks: write
  deployments: write
  discussions: write
  id-token: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        uses: actions/checkout@v3
      - name: Setup-deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run
        run: |
          echo ::group::Deno cache
          deno run -A ./.github/scripts/publish.ts
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
