name: CI
on:
  workflow_call:
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Script
        uses: asnowc/actions@deno-script/v1
        id: cc2
        with:
          args: -A
          script: |
            import { setOutput } from "npm:@actions/core";
            import { writeNewTagToOutput } from "https://cdn.jsdelivr.net/gh/dnpack/action-script@0.3.0/cmd/github_repo.ts";
            writeNewTagToOutput("v13.4", "RES");
      - name: A
        if: ${{!steps.cc2.outputs.script_output}}
        run: echo ${{steps.cc2.outputs.script_output}}

      - name: B
        if: ${{steps.cc2.outputs.script_output}}
        run: echo ${{steps.cc2.outputs.script_output}}
