name: manual
on:
    workflow_dispatch:
        inputs:
            tags:
                description: 发布标签
                required: false
                type: boolean

jobs:
    beta:
        if: ${{ inputs.tags }}
        runs-on: ubuntu-latest
        steps:
            - name: Publish Npm package
              run: echo ${{ secrets.NPM_TOKEN }}
    release:
        if: ${{ inputs.tags }}
        runs-on: ubuntu-latest
        steps:
            - name: Publish Npm package
              run: echo fin
