name: Publish Npm Package
on:
    pull_request_target:
        types:
            - closed
        branches:
            - main

jobs:
    build:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/workflows/unit-test.yaml
            - name: Publish Npm package
              run: pnpm publish --tag rc --publish-branch release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
