name: pull request
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: npx
        continue-on-error: true
        run: npx jsr publish --dry-run
      - name: deno
        run: deno publish --dry-run
