name: pull request
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Package npm
        run: |
          {
            echo 'PACKAGE_JSON<<EOF' 
            cat ./package.json
            echo EOF
          } >>  $GITHUB_ENV
          echo ${{fromJson(env.PACKAGE_JSON).version}}
