name: pull request
on:
    pull_request:
        types:
            - opened
            - reopened

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ GITHUB_REF }}
            - name: Publish Npm package
              run: git branch
