name: pull request
on:
    workflow_call:
env:
    ARTIFACT_NAME: dist_${{github.ref_name}}
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: prepare
              uses: actions/checkout@v3
            - name: package
              run: tar -cvf up.tar src/*
            - name: upload
              uses: actions/upload-artifact@v3
              with:
                  name: ${{env.ARTIFACT_NAME}}
                  path: up.tar
