name: pull request
on:
    # pull_request:
    #     types:
    #         - opened
    #         - reopened
    #     branches:
    #         - release
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: asnow-c/template@v1
              with:
                  nodev: 20
                  pnpmv: 8
                  run_install: true
            - name: build
              run: pnpm build
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Unit test
              run: pnpm test
            - name: view
              run: ls
            - name: pwd
              run: pwd
