name: pull request
on:
    pull_request:
        types:
            - opened
            - reopened

jobs:
    build:
        if: github.event.review.state == 'approved'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Publish Npm package
              run: git branch
