name: manual
on:
    push:

jobs:
    beta:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/workflows/callable.yml
            - run: echo ok
              name: "echo"
