name: Review
on:
    pull_request_review:
        types:
            - submitted

jobs:
    build:
        if: github.event.review.state == 'approved'
        runs-on: ubuntu-latest
        steps:
            - name: Publish Npm package
              run: echo okkk
